# Generated by Django 6.0.6 on 2026-08-17 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='postulation',
        ),
        migrations.DeleteModel(
            name='Postulation',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
