# Generated by Django 6.0.6 on 2026-08-17 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_remove_work_postulation_delete_postulation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulation',
            fields=[
                ('id_postulation', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('postulation_date', models.DateTimeField(auto_now_add=True)),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulations', to='projects.project')),
                ('id_tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id_project', 'id_tester'), name='unique_postulation')],
            },
        ),
    ]
