# Generated by Django 6.0.6 on 2026-08-25 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postulations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id_report', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('risk_level', models.CharField(max_length=50)),
                ('capture_evidence', models.FileField(blank=True, null=True, upload_to='reports/evidence/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEW', 'Review'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('id_postulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='postulations.postulation')),
            ],
        ),
    ]
