# Generated by Django 6.0.6 on 2026-08-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='id_report',
        ),
        migrations.AddField(
            model_name='report',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='report',
            name='steps_to_reproduce',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='capture_evidence',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='risk_level',
            field=models.CharField(default='LOW', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='state',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
