# Generated by Django 6.0.6 on 2026-08-17 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postulations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id_rating', models.BigAutoField(primary_key=True, serialize=False)),
                ('stars', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_postulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='postulations.postulation')),
            ],
        ),
    ]
